.\"
.\" Man page for bibcursed
.\"
.\" Copyright (c) 1999 - 2007 Dominic Tristram
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the README file that comes with the
.\" distribution.  
.\"
.\" Dominic Tristram
.\" dominic@dominictristram.com
.\"
.TH BIBCURSED 1 "27th September, 2007"
.LO 1

.SH NAME
bibcursed \- manipulate BibTeX files

.SH SYNOPSIS
bibcursed bibtex_file

.SH DESCRIPTION
.B bibcursed
Performs various actions on BibTeX files, from error checking to editing

.SH OPTIONS
.TP
There are no options in this version. The name of the BibTeX file, given
as the sole command line argument, is *required*.

.SH ENVIRONMENT
.TP
No environment variables are used

.SH DIAGNOSTICS
All errors are sent to stdout

.SH "SEE ALSO"
latex(1).

.SH COPYRIGHT
bibcursed is Copyright (c)1999-2007 Dominic Tristram. It is subject to the GNU
General Public Licence

.SH BUGS
See the bug tracking page at http://sourceforge.net/projects/bibcursed/

.SH AUTHORS
Dominic Tristram - dominic@dominictristram.com - http://www.dominictristram.com/

